# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TheoryProj-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheoryProj-desktop

end

target 'TheoryProj-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheoryProj-mobile

end
